version: '2'

services:
  ratmachine:
    build: .
    image: ratmachine
    command: amber watch
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/ratmachine_development
      RATMACHINE_MOD_USERNAME: wojak
      RATMACHINE_MOD_PASSWORD: tfwnogf
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
    volumes:
    - .:/app
    - shards:/app/lib

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ratmachine_development
    volumes:
      - db:/var/lib/postgres/data

volumes:
  db:
  shards:
