secret_key_base: uOoEVahkitYzJyX5ebXcgY9hmEUIUzefzsl-pQNkIHE
port: 3000
name: ratmachine

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: false
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: postgres://admin:password@db:5432/ratmachine_test

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.
